"""email stuff

Revision ID: f3b8d6d38b0b
Revises: 6575522c7b4d
Create Date: 2025-11-30 00:08:50.938079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b8d6d38b0b'
down_revision: Union[str, Sequence[str], None] = '6575522c7b4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
